default: &default
  adapter: postgresql
  encoding: unicode
  host: db
#  host: localhost
  username: postgres
  password: password
#  password: postgres
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test
